version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: peaknote-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: peaknote
      MYSQL_USER: peaknote
      MYSQL_PASSWORD: peaknote123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: peaknote-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 3s
      retries: 5

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: peaknote-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
  redis_data:
  rabbitmq_data: